---
apps:
  - name: "strawberries"
    html: |
      <body>
        <h1>J'aime beaucoup les fraises</h1>
        <p>They're jamming!</p>
      </body>
    public: true
  - name: "bananas"
    html: |
      <body>
        <h1>This is Bananas!</h1>
        <p>Seriously, this is bananas.</p>
      </body>
    public: false
  - name: "apfeln"
    html: |
      <body>
        <h1>An apple a day keeps the doctor away</h1>
        <p>But only if you aim correctly and throw it really hard.</p>
      </body>
    public: false
