---
apps:
  - name: "strawberries"
    html: |
      <html>
        <head>
          <meta charset="utf-8"/>
        </head>
        <body>
          <h1>ğŸ“ Strawberries playing music together</h1>
          <p>They're jamming!</p>
        </body>
      </html>
    public: true
  - name: "bananas"
    html: |
      <html>
        <head>
          <meta charset="utf-8"/>
        </head>
        <body>
          <h1>ğŸŒ This is Bananas!</h1>
          <p>Seriously, this is bananas.</p>
        </body>
      </html>
    public: false
  - name: "apples"
    html: |
      <html>
        <head>
          <meta charset="utf-8"/>
        </head>
        <body>
          <h1>ğŸ An apple a day keeps the doctor away</h1>
          <p>But only if you aim correctly and throw it really hard.</p>
        </body>
      </html>
    public: false
